spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  output:
    ansi:
      enabled: always

server:
  address: 0.0.0.0
  port: ${PORT:8080}

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://7b91ff33abaa5e9940187d2b39bd28e7@o4506961914691584.ingest.us.sentry.io/4506961975443456
  tracesSampleRate: 1.0
  exception-resolver-order: -2147483647